### ISSUE TITLE
Function remove_duplicate in star_handler

### ISSUE THREAD

**Issue by ShelvinZhang** [3dem/relion#1054]
Hi,

I found something strange in the code of the remove_duplicate function:

                RFLOAT particle_angpix = 1.0; // rlnOriginX/YAngst is always 1 A/px.

Obviously it is not correct and can not be overriden using --angpix.

**Comment by biochem-fan** [comment]
This is correct, although the unit is indeed misleading. It should read "always 1 A/unit".

In older versions of RELION, we had `rlnOriginX/Y` instead of `rlnOriginX/YAngst`.
In those days, this variable represented the real angstrom/pixel.
With the introduction of `rlnOriginX/YAngst`, one count corresponds to 1 A by definition, so this variable is always 1.0.
