### ISSUE TITLE
Class2D crash: Too many fail-safe attempts in one iteration

### ISSUE THREAD

**Issue by bforsbe** [3dem/relion#155]
Originally reported by: **Dimitry Tegunov (Bitbucket: [DTegunov](https://bitbucket.org/DTegunov), GitHub: [DTegunov](https://github.com/DTegunov))**

----------------------------------------

2D classification crashed after 8 iterations. Continuing from last iteration works for 1–2 iterations, then crashes again with same error, and so on. I'm attaching the job/out/err files.

----------------------------------------
- Bitbucket: https://bitbucket.org/tcblab/relion2-beta/issue/155

**Comment by ilahiri** [comment]
Hi
I recently ran into the same issue when running a 2D classification job using relion2.0. I am running the latest stable version of relion from github (downloaded February 26, 2017) and the job was run in GPU mode and I got the following warning message (many of them) followed by a Segmentation fault.

WARNING: Exception (filteredSize == 0) handled by switching to fail-safe mode

I plan to rerun the job using the flag --maxsig 500 (as mentioned in this thread) and was wondering if I still need to install the patch nofailsafecap.patch or if it is included in the latest version of relion?

**Comment by lauravanbezouwen** [comment]
Hi,

I got the same comment as here. We have version2.0.5. I have tried the maxsig 500 but then it still happened. We have updated relion this morning to the newest version. If I want to continue my job it happened again after 1 iterations. For now I have decided to split my job in good and bad particles and just do an other 2D classification on what seems the good particles and hopefully be still able to discard all the junk. I hope it will solve the problem for me. But as asked I just wanted to let you know.

Best wishes
Laura

 github.com/3dem/relion/issues  
 ) handled by switching to fail-safe mode.

WARNING: Exception (ERROR: 
No orientation was found as better than any other.

A particle image was compared to the reference and resulted in all-zero
weights (for all orientations). This should not happen, unless your data
has very special characteristics. This has historically happened for some 
lower-precision calculations, but multiple fallbacks have since been 
implemented. Please report this error to the relion developers at 

	         github.com/3dem/relion/issues  
 ) handled by switching to fail-safe mode.
[cryo-em1:24401] *** Process received signal ***
[cryo-em1:24401] Signal: Segmentation fault (11)
[cryo-em1:24401] Signal code: Address not mapped (1)
[cryo-em1:24401] Failing at address: 0x20c4
[cryo-em1:24401] [ 0] /usr/lib64/libpthread.so.0(+0xf370)[0x7f01bfa07370]
[cryo-em1:24401] [ 1] /usr/lib64/libstdc++.so.6(_ZNSsC1ERKSs+0x1b)[0x7f01c01eaf4b]
[cryo-em1:24401] [ 2] /opt/RELION2/lib/librelion_lib.so(_ZN11RelionErrorC2ERKS_+0x1f)[0x7f01cadd1cbf]
[cryo-em1:24401] [ 3] /opt/RELION2/lib/librelion_lib.so(_ZN11MlOptimiser24expectationSomeParticlesEll+0x12c0)[0x7f01cadbd740]
[cryo-em1:24401] [ 4] /opt/RELION2/lib/librelion_lib.so(_ZN14MlOptimiserMpi11expectationEv+0x143a)[0x7f01caddf09a]
[cryo-em1:24401] [ 5] /opt/RELION2/lib/librelion_lib.so(_ZN14MlOptimiserMpi7iterateEv+0x5d)[0x7f01cade776d]
[cryo-em1:24401] [ 6] /opt/RELION2/bin/relion_refine_mpi(main+0x69)[0x40a159]
[cryo-em1:24401] [ 7] /usr/lib64/libc.so.6(__libc_start_main+0xf5)[0x7f01bf658b35]
[cryo-em1:24401] [ 8] /opt/RELION2/bin/relion_refine_mpi[0x40a2bf]
[cryo-em1:24401] *** End of error message ***

**Comment by bforsbe** [comment]
Thanks! 
This might happen for particles which get translated (due to fitting over many iterations) very far from the extracted center-point. If this is indeed the case, performing a re-extraction of the data (using the most recebt iteration _data.star file) with re-centering should get rid of this error.

**Comment by biochem-fan** [comment]
Old version.
