### ISSUE TITLE
2D Classification Stalling on GPU

### ISSUE THREAD

**Issue by bforsbe** [3dem/relion#166]
Originally reported by: **Bharat Reddy (Bitbucket: [barureddy](https://bitbucket.org/barureddy), GitHub: [barureddy](https://github.com/barureddy))**

----------------------------------------

When I run 2D Classification using my gpus I get an error with relion stalling before it reaches the 25 iterations. The master thread still runs in a zobie like process. My issue looks like #24, but I am not sure. The particle files are quite large, but I can upload them to you if needed. 

----------------------------------------
- Bitbucket: https://bitbucket.org/tcblab/relion2-beta/issue/166

**Comment by bforsbe** [comment]
The original (stalling execution during last phase of an expectation step) is fixed in v2.0.4. It resulted from using threads in an inherently unsafe manner within the cuda-context. During fast enough runs, this led to occasional deadlock in cuda-internal pthread-mutex locks. This also explins why decreasing pool helps; it decreases thread-based parallelism and the concurrency which caused the stall.

**Comment by truatpasteurdotfr** [comment]
I have been hitting something which could be this issue, while running relion (2.0.3/openmpi 1.10.6/CentOS-6) benchmaks on a single 16 cores/2 sockets 4x titanX pascal: random (non reproduceable) stalled jobs 100% cpus/gpus (1/2/4)...

**Comment by bforsbe** [comment]
Sounds like it is. Updating the code according to the instructions on the landing page should eliminate this.

**Comment by bforsbe** [comment]
``` --maxsig 500 ```  (note: no underscore) will force relion to consider at most 500 orientations for a finer sampling. You still perform an exhaustive (all orientations) according to your settings, so maxsig is a fairly safe optimization strategy. The lower you set maxsig, the more confidence you place in the statement "**the best orientational fits are found in the true/correct alignment**". Note that the 'fit' is something we calculate to estimate orientation, but which may be noisy or have false peaks. However, I have run with maxsig as low as 5 in 2D without trouble, and as low as ~300 in 3D. If results look strange, I'd recommend validation, by running again with a higher maxsig, but generally it does not significantly alter the results, unless your data is really poor quality.

**Comment by davboyer** [comment]
Hello @bforsbe ,

I am using Relion 2.1.0 with OpenMPI 3.0.0 and I believe I am having all the symptoms of this problem.

When I run large 2D classifications (800,000 particles, box size 320), I get hang ups on one GPU as described above while the others are inactive.

This problem seems to be stochastic, as I have run a very similar job with the same particles, and it went through 25 iterations.

However, after it happens once and I cancel the job, subsequent jobs seem to recapitulate the problem, and for a few days, many jobs I run with more than 50k or 100k particles get stuck at one of the expectation iterations. There is no error message, and the job hangs up indefinitely.

I am currently trying the a job that just suffered from this problem with the --pool 1 option to see if it helps.

I know you said this problem was fixed as of v2.0.4, but I am still struggling with it. Any advice? Thanks!

**Comment by bforsbe** [comment]
Did you try rebooting the computer? Sounds like a memory (RAM) issue.

**Comment by bforsbe** [comment]
RELION is not completely deterministic in its results, but getting any error completely stochastically rather hints at some hardware-flaw that you hit. It could still be in the algorithm, but a lot of people are using the algorithm, and only you are using your hardware. 

That being said, I don't actually know what error you are getting. This is a long and convoluted thread and "as the above" is unfortunately not very descriptive, in part because at least one false observation was given at some point.

**Comment by davboyer** [comment]
@bforsbe My apologies for the lack of clarity. I believe my issue is more similar to #53 and #54 (please let me know how to move my comments if that would help clarity). 

It appears in issue #53 that Ozkan Yildiz had the same problem I was having; namely, the 2D classification would _stall at the very last part of the expectation step with no error message_. 1 GPU would show 100% utilization (although low wattage) while the others have 0% utilization and no memory used. Ozkan seemed to have solved this problem by using a different data set before the discussion diverged into talking about GPU indexing... Although this problem seemed to manifest again for Ozkan (comment at the end of issue #53), and was solved by omitting the flag --dont_combine_weights_via_disc in Relion 1.4. However, Ozkan comments on December 16, 2016 (issue #54) that the problem has resurfaced and that they resorted to using CPU's to avoid this problem all together (comment in issue #54 towards middle of page). Finally, Ozkan mentioned that using --pool 1 alleviated the stalling GPU problem.

In issue #54, @cdk reported that they were having a problem with a job crashing, yet a GPU still running. This would lead users to starting new jobs and getting memory allocation errors. However, @cdk did not follow-up with much information regarding the current state of that problem for them. 

At the end of #54, @bforsbe stated that "Using v2.0.4 you should no longer find zombies, as the issue was identified and fixed. It was caused by not-so cautious use of htread-parallelism in a single cuda-context, which in turn caused some dead-locks in internal cuda-threads. The zombie was thus a spin-lock in cuda waiting to return an API-call."

However, I am not sure if there is a difference between a zombie still running on the GPU after a job "crashes" and what I am seeing where the job never technically "crashes," but remains stuck at the last part of an expectation step indefinitely with one GPU at 100% and all others going to 0%. 

I have re-started our GPU nodes, and re-run the job starting at the iteration immediately before the crash (iteration 3). The job is now on iteration 6 and seems to be operating successfully. I tracked the buff/cache memory over the course of the run using the command free as I was curious about the RAM. After reboot, buff/cache was empty, and over the several iterations it is now close to ~114-120 GB on all the GPU nodes (we have 128 GB of RAM on each GPU node). Thank you for your tip regarding rebooting the machines. 

Is there any other information I can provide to you so that we may nail down the problem? I have run many successful 2D and 3D classifications; however, this problem is the only one I get in Relion that doesn't produce an error message and leaves me sort of clueless as to what is happening. Any help is appreciated. Thanks!

**Comment by bforsbe** [comment]
I'm pretty certain your issue is not a lockup as fixed in issue #54, just to have that said. 

Relion dispatches mpi-slaves and waits for them to return before continuing. Anytime a slave get stuck doing anything, the symptoms are largely the same, which is why many issues look the same. The interesting observation in your case is the 100% gpu util. 

Now, that does not mean that they are working hard, just that the slave got stuck in a state where the gpu was busy. So network dropouts or RAM-swapping is actually quite unlikely. Thinking about it again, the gpu-driver or cuda-runtime are more likely to have dropped out or ended up in a weird state. The first debug for this is, yep, a reboot. 

I don't like to say that this is the issue, because it's not something I can fix. But it's looking likely, unless you have further issues. Let me know if that's the case and we'll try to dig deeper. 

Thanks for the simply splendid clarification! Your in my good book.

**Comment by davboyer** [comment]
@bforsbe Thanks for the reply! No problem, writing the summary of the other issues actually helped me clarify the issue myself.

Just for completeness, I will post my newest set of experiments that may help confirm the issue. All of these experiments were run across 7 nodes, each with one GPU card (2 1080's and 5 1080 Ti's), using mpi and 8 mpi processes per card (except the first node which has 7 procs per GPU due to mpi master being on this node; I am using SLURM, therefore the first cpu gets assigned to master, and the other seven go to slaves on node 1). The particles.star file contained ~800k particles with a box size of 320 pixels (1.07 A/pix).

To determine if rebooting computers solved the problem, we rebooted all the nodes and ran my 2D classification. The result was that the job ran successfully through 25 iterations.

To determine if having buffer/cache "full" at start of job is causing problems versus some cuda or gpu-driver problem, we re-ran the same 2D classification without doing anything additional to the computers. The buff/cache memory was almost full (~115GB on 128 GB RAM nodes) at the start of the job, and I checked to make sure there were no zombie processes on any node before running the job. The result was that the classification hangs at the end of iteration 4 with all the usual symptoms (2 of the 1080 Ti's stalling at end of expectation with 100% GPU util, 75W/280W, and 10Gb/11Gb GPU memory used. All other GPU's are empty, 0% util, no memory used, etc.).

To further investigate the role of RAM in this problem, we cleared the caches without rebooting the nodes and performed the same classification (again, checking for any sort of zombie processes). The result was that the classification hangs at the end of expectation 2. This time with a different 1080 Ti hanging at 100% util. (Note: I have performed similar experiments, and it is never the same GPU that stalls at the end of the expectation, the problem appears to happen indiscriminately among 1080's and 1080 Ti's among the nodes).

Does this to you vindicate any sort of RAM issue causing the problem and place the blame again on the gpu-driver or cuda-runtime doing something weird at the last part of expectation step? Any additional thoughts? Thanks!

**Comment by bforsbe** [comment]
8 MPI-ranks per GPU is more than I have ever run. For 2D-classification, you CAN of course do that because the memory footprint of 2D-images is so much less than that of 3D-models, but I would think that there's not much performance to get from having that many. 

I can try to reproduce by simply crowding a GPU with an insane number of MPIs and see if there's some contention or race-condition we missed across MPIs. My advice in the meantime is to scale back to one or two MPIs per GPU and pack on the threads instead. 

For 2D, I tend to just 

1. Downscale particles to ~50-100 pixels,
2. Not use MPI at all (stick to one node) (you can use many GPUs without MPI, as long as you have multiple threads)
3. Use a subset-setting corresponding to ~100-200 particles/class for ~5 iterations
4. Set the --maxsig flag to ~5-20

With those settings, most things fly through pretty darn quick, even on one GPU. It avoids MPI-communication overhead and RAM-caches everything. Gets the job done. Some choose to linger and perfect their 2D-classes, but this is time wasted in my mind, especially for initial cleaning of otherwise good data.

**Comment by davboyer** [comment]
@bforsbe Thanks for the suggestions! I talked to a very experienced colleague yesterday, and he says he usually has does 3-4 MPI procs per GPU for 2D with no problems (but he definitely did not like the idea of 8 mpi per gpu!). I will definitely lower the number of mpi procs per GPU in the future, and try your other suggestions.

**Comment by davboyer** [comment]
Hi @bforsbe ,

I am wondering if there is a way to include "-G" (big G) option for nvcc for cuda kernel debugging? I am still debugging this issue. It doesn't seem that DCMAKE_BUILD_TYPE=Debug enables -G for nvcc unless I'm mistaken...

My current workaround is to use --continue when jobs get stuck on an iteration. This usually pushes them through until they finish, or if they get stuck again at a later iteration, then I do --continue again until all iterations are done.

**Comment by bforsbe** [comment]
read line 5 of Cmake/BuildTypes.cmake. 

Of note, you might also have to set ```-DBUILD_SHARED_LIBS=OFF``` for gdb to read the symbols ok.

**Comment by adil-20** [comment]
Hi guys, I hope you doing well all, I new on using RELION 3.1, I'm facing some issues on using 2D classification on RELION 3.1 I did follow the installation and try to run the GUI it did work but when I tried to run the 2D classification it did not work, I wen back to the comment line approach and download the benchmark dataset with the STAR file and when I tried to run the following comment:

mpirun -n XXX `which relion_refine_mpi` --i Particles/shiny_2sets.star --ctf --iter 25 --tau2_fudge 2 --particle_diameter 360 --K 200 --zero_mask --oversampling 1 --psi_step 6 --offset_range 5 --offset_step 2 --norm --scale --random_seed 0 --o class2d

I got the following error:
![Screenshot from 2020-09-26 15-38-19](https://user-images.githubusercontent.com/71946383/94349869-69d45f80-000e-11eb-9aca-8587195397a3.png)

please could someone help me how to run the 2D classification in RELION 3.1 really appreciate that!
@bforsbe

**Comment by davboyer** [comment]
Hi, you cannot use the XXX when you run from the command line. You need to
specify an actual number of mpi tasks. XXX type variables only work when
you are using a template script for the Relion GUI to fill in the variables
with values from the gui.
