### ISSUE TITLE
.Nodes directories have files, but files empty

### ISSUE THREAD

**Issue by Tom-Ceska** [3dem/relion#190]
I like the way the .Nodes directories are created, to help with selecting the correct file for the next step. But for some reason when I click on the file, it says 'empty file' in the preview window. I then have to navigate up to the project directory to get to the correct job type and job number. If I do that, the preview window shows actual contents for the next job.

**Comment by bforsbe** [comment]
When you "schedule" a job for execution, relion creates an empty output file so that you can specify it as input for a subsequent (scheduled) job. Is this the context in which you observe this? I'm afraid I don't understand what you mean by your last statement, what is the "next job" exactly, and what contents do you see that you didn't see originally?
