### ISSUE TITLE
3D classification crashes 

### ISSUE THREAD

**Issue by YehudaHalfon** [3dem/relion#194]
Hi all,
I'm running a 3D classification ~130K particles in the 11th iteration it crashes. I get this in the log file:

 Expectation iteration 11 of 25
20.87/47.57 min ..........................~~(,_,">--------------------------------------------------------------------------
mpirun noticed that process rank 1 with PID 28325 on node ribos21l exited on signal 11 (Segmentation fault).

And in the err file many repeats of this:
WARNING: Exception (filteredSize == 0) handled by switching to fail-safe mode.

Thanks,
Yehuda Halfon

**Comment by bforsbe** [comment]
Do the classes all look reasonable after iteration 10?

**Comment by YehudaHalfon** [comment]
yes, they do look reasonable.

**Comment by YehudaHalfon** [comment]
Apparently when I did it again, after extract at bin4, it works. 
So I believe that this hard for our station to do it at bin0.

**Comment by bforsbe** [comment]
This is a plague of an error, which may occurs due to rare and physically incorrect values in the references. This is just one of the theories though, since it's difficult to replicate. Chances are that running again with bin0 and choosing some other --random_seed would also work. However, if you can afford to run at bin4, then that is much better in terms of efficiency anyway.
