### ISSUE TITLE
system-wide installation not working.

### ISSUE THREAD

**Issue by ScarabMonkey** [3dem/relion#197]
Following the instructions here does not produce a portable installation of relion:
http://www2.mrc-lmb.cam.ac.uk/relion/index.php/Download_%26_install#Specifying_an_installation_location
This is because the 'make install' does not properly honour that directory for the extra libraries (FLTK/FFTW)

Related issue:
The apps (e.g. relion_refine) are built in a slightly different way from the main 'relion' executable - they do honour this choice better - the relion executable seems to hard-code the 'external/fftw' path rather then use the LD path.

**Comment by ScarabMonkey** [comment]
I have made a pull request #196 which I believe fixes the main problem here.

**Comment by ScarabMonkey** [comment]
FYI: this was being built on a CentOS 6 machine with:
cmake -DFORCE_OWN_FFTW=ON -DFORCE_OWN_FLTK=ON -DCMAKE_INSTALL_PREFIX=/usr/mbu/software/relion/relion-2-test ..

**Comment by bforsbe** [comment]
Sorry for not picking up this sooner. I'll try your suggested changes out and let you know. It's really good of you to submit a pull-req, because it's much easier for us to implement and test. But just to make you aware, when we incorporate any suggested new changes into the code, it's typically into our devel-repo since this is already ahead of 2.0.3. But do leave the pull-req, and I'll check it out asap.

**Comment by truatpasteurdotfr** [comment]
@ScarabMonkey thanks for looking at it, I was working around with a quick/dirty rsync -aPHSRv external/*/lib $PREFIX and  LD_LIBRARY_PATH/LD_RUN_PATH.

**Comment by ScarabMonkey** [comment]
I have just built the 2.1 beta and encountered exactly the same problem.
This time the make install did successfully copy the fltk libraries ... but not the fftw ones!
I had to copy them manually.

**Comment by biochem-fan** [comment]
Probably fixed by now.
