### ISSUE TITLE
Ordering by class distribution bug

### ISSUE THREAD

**Issue by olibclarke** [3dem/relion#241]
In relion 2.1, sorting particles by class distribution using relion_display doesn't work exactly as expected. The largest classes are still more or less at the top, but further down the list they are not strictly ordered by class distribution - e.g. I have a class with one particle, then another class with several hundred particles, then another class with one particle.

**Comment by olibclarke** [comment]
Checking the Class distribution parameter with "show metadata" it seems to be sorting on this parameter, but the number of particles doesn't tally with the ordering. Likewise when sorting by rotations - some obviously high resolution classes have estimated accuracy of rotations of 999 degrees, which makes me think something has got mixed up. I am using the new feature of Class2D which allows speeding up the initial iterations by splitting into subsets, in case that makes a difference.

**Comment by bforsbe** [comment]
Class distribution means the cumulative weight given by all particles. 

Say I run with 100 particles. If 100 of those particles give 40% of their weight to a class and no other particles contribute to that class, then the class will have a "class distribution"-value of 0.4*100 / 1000 = 0.04. If, in addition, all of those particles contribute more than 40% of their weight to some other class, then non of them will "belong" in that class, even though "4% of 100 particles", were "assigned" to that class. 

This is to say; you can have a "class distribution" which indicates an effective particle number which is higher than the actual particle number. This is because RELION does not assign particles to classes, but splits them by weight. However, to split datasets by classification, we need some sort of separation, and relion goes by the class to which a particle contributed most.

**Comment by olibclarke** [comment]
Hi Björn - thanks for the explanation - I still think there is something odd going on, because when sorting by accuracy of rotations, obviously high resolution classes with secondary structural features are scattered amongst obvious junk classes, which I cannot recall happening with 2.06.

**Comment by bforsbe** [comment]
I'll keep it in mind, but I have seen similar effects before as well. The accuracy of rotations and so on is not the most reliable feature, and not one to be taken as ground truth of quality, and I think you might be seeing an example of this rather than an incorrect sort. I'll keep my eyes open though! Thanks!
