### ISSUE TITLE
image number 117 exceeds stack size 116 of image 118

### ISSUE THREAD

**Issue by joe-batchelor** [3dem/relion#273]
Hi,

This error came up in a 3D classification. It was resolved by re-extracting particles. Then it came up again the next day on the re-extracted particles and was resolved by re-extracting a third time. Anyone know what this is about?

Thank you!
Joe

**Comment by bforsbe** [comment]
Sounds like an previous thing, where you import micrographs from outside the relion directoy. This results in a leading ".." in the path used in the particle.star file. This in turn leads to re-extractions over-writing any previous extractions because the images are stored in Extract/dir, rather than Extract/jobXXX/dir. 

I describe it more detail in a post dated january 12th, in issue #143 

Let me know if you think it's something else, but it sound just like that. The key is to **always import data from within the relion project directory**. If you want to keep your data somewhere else, it's better to make a symbolic link or shortcut to the data, within the project directory, instead of importing it from outside.

**Comment by joe-batchelor** [comment]
Thank you for the quick response! Yes, image files are outside the relion project directory. I will fix this, thank you.
