### ISSUE TITLE
Ctffind4.1 is not working on relion2.1beta

### ISSUE THREAD

**Issue by psryubh** [3dem/relion#276]
As the title is, Ctffind4.1 is not working on relion2.1beta(b0 or b1 whatever..)

Running ctf estimation job with Ctffind4.1 produced empty micrographs_ctf.star file, although Run.err file said just "warning". 

Briefly, two types of warning come; 
**1) error in executing csh
2) skipping, cannot get CTF value**

However, Gctf works fine, and therefore I guess this is not simple input error but some problem in relion(specifically, the ctf estimation function or related script?) when it communicates with ctffind4.1. Since I am a kind of novice, I cannot solve out this issue.

How can I solve out?

**Remark** : this issue is slightly different with #186  in the following 2 aspects.
**1) The difference to #186 that produced the same errors with my case, is that I could get ctf estimation with Gctf(v1.6) successfully. 
2) Plus, nothing have done with ctffind4.1, resulting in empty *_ctf.star file. And even repetition of the job did not work at all, which is unlike the solution suggested in #186; repeat this until all micrographs is done.**

The following are the details of the Note.txt, Run.out and Run.err files.

**Note.txt**
------------------------------------------
 ++++ Executing new job on Fri Aug 18 11:31:23 2017
 ++++ with the following command(s): 
`which relion_run_ctffind` --i ./MotionCorr/job002/corrected_micrographs.star --o CtfFind/job003/ --CS 0.002 --HT 300 --AmpCnst 0.1 --XMAG 10000 --DStep 1.4 --Box 512 --ResMin 30 --ResMax 5 --dFMin 5000 --dFMax 50000 --FStep 500 --dAst 100 --ctffind_exe "/home/sbl/relion_acc/ctffind-4.1.8/ctffind --omp-num-threads 1 --old-school-input" --ctfWin -1 --is_ctffind4  
 ++++ 
------------------------------------------

**Run.out**
------------------------------------------
 Using CTFFIND executable in: /home/sbl/relion_acc/ctffind-4.1.8/ctffind --omp-num-threads 1 --old-school-input
 to estimate CTF parameters for the following micrographs: 
  * MotionCorr/job002/rawframes/P97-fullcomplex_0005.mrc
  * MotionCorr/job002/rawframes/P97-fullcomplex_0006.mrc
  * MotionCorr/job002/rawframes/P97-fullcomplex_0007.mrc
 Estimating CTF parameters using Alexis Rohou's and Niko Grigorieff's CTFFIND4.1 ...
   0/   0 sec ............................................................~~(,_,">
 Done! Written out: CtfFind/job003/micrographs_ctf.star
------------------------------------------

**Run.err**
------------------------------------------
sh: 1: csh: not found
WARNING: there was an error in executing: csh CtfFind/job003/rawframes/P97-fullcomplex_0005_ctffind4.com
sh: 1: csh: not found
WARNING: there was an error in executing: csh CtfFind/job003/rawframes/P97-fullcomplex_0006_ctffind4.com
sh: 1: csh: not found
WARNING: there was an error in executing: csh CtfFind/job003/rawframes/P97-fullcomplex_0007_ctffind4.com
 WARNING: skipping, since cannot get CTF values for MotionCorr/job002/rawframes/P97-fullcomplex_0005.mrc
 WARNING: skipping, since cannot get CTF values for MotionCorr/job002/rawframes/P97-fullcomplex_0006.mrc
 WARNING: skipping, since cannot get CTF values for MotionCorr/job002/rawframes/P97-fullcomplex_0007.mrc
------------------------------------------

**Comment by ashkumatov** [comment]
had a same error. You simply have no c-shell on your machine. please install
the tcsh package and it will work. csh (and its improved version tcsh) are shell script programms similar to bash which is (almost) exclusively used by current linux distributions.
HTH, Alex

**Comment by psryubh** [comment]
Dear Alex,

Thank you for your kind advice. 

However, ctffind4.1 did not work even after I have installed tcsh. 

It seems like the problem is not that simple.

Somehow, I appreciate your concern.



Sincerely,
Han




Bum Han Ryu

Ph.D student (Combined)
Structural Biology LAB.,
Dept. of Molecular Cell Biology, Sungkyunkwan University School of Medicine,
Suwon, South Korea

**Comment by ashkumatov** [comment]
Hey Han
what is the error message you are getting now? what do you get when typing in command line "csh"?
Alex

**Comment by psryubh** [comment]
Exactly the same message I left top above.

When I typed csh in command line, I found just 
**sbl:~%**
and That's all. It seems like csh works normally.
Should I run relion and CTFFIND on that csh shell mode?


Han

**Comment by baibing7713661** [comment]
I got the similar error and did not get how to solve it.

run.err
../../../../../home/admin/relion/build/bin/ctffind: error while loading shared libraries: libtiff.so.3: cannot open shared object file: No such file or directory
../../../../../home/admin/relion/build/bin/ctffind: error while loading shared libraries: libtiff.so.3: cannot open shared object file: No such file or directory
../../../../../home/admin/relion/build/bin/ctffind: error while loading shared libraries: libtiff.so.3: cannot open shared object file: No such file or directory
../../../../../home/admin/relion/build/bin/ctffind: error while loading shared libraries: libtiff.so.3: cannot open shared object file: No such file or directory
../../../../../home/admin/relion/build/bin/ctffind: error while loading shared libraries: libtiff.so.3: cannot open shared object file: No such file or directory
../../../../../home/admin/relion/build/bin/ctffind: error while loading shared libraries: libtiff.so.3: cannot open shared object file: No such file or directory
../../../../../home/admin/relion/build/bin/ctffind: error while loading shared libraries: libtiff.so.3: cannot open shared object file: No such file or directory
../../../../../home/admin/relion/build/bin/ctffind: error while loading shared libraries: libtiff.so.3: cannot open shared object file: No such file or directory
../../../../../home/admin/relion/build/bin/ctffind: error while loading shared libraries: libtiff.so.3: cannot open shared object file: No such file or directory
../../../../../home/admin/relion/build/bin/ctffind: error while loading shared libraries: libtiff.so.3: cannot open shared object file: No such file or directory
../../../../../home/admin/relion/build/bin/ctffind: error while loading shared libraries: libtiff.so.3: cannot open shared object file: No such file or directory
../../../../../home/admin/relion/build/bin/ctffind: error while loading shared libraries: libtiff.so.3: cannot open shared object file: No such file or directory
../../../../../home/admin/relion/build/bin/ctffind: error while loading shared libraries: libtiff.so.3: cannot open shared object file: No such file or directory
../../../../../home/admin/relion/build/bin/ctffind: error while loading shared libraries: libtiff.so.3: cannot open shared object file: No such file or directory
../../../../../home/admin/relion/build/bin/ctffind: error while loading shared libraries: libtiff.so.3: cannot open shared object file: No such file or directory
../../../../../home/admin/relion/build/bin/ctffind: error while loading shared libraries: libtiff.so.3: cannot open shared object file: No such file or directory
../../../../../home/admin/relion/build/bin/ctffind: error while loading shared libraries: libtiff.so.3: cannot open shared object file: No such file or directory
../../../../../home/admin/relion/build/bin/ctffind: error while loading shared libraries: libtiff.so.3: cannot open shared object file: No such file or directory
../../../../../home/admin/relion/build/bin/ctffind: error while loading shared libraries: libtiff.so.3: cannot open shared object file: No such file or directory
../../../../../home/admin/relion/build/bin/ctffind: error while loading shared libraries: libtiff.so.3: cannot open shared object file: No such file or directory
../../../../../home/admin/relion/build/bin/ctffind: error while loading shared libraries: libtiff.so.3: cannot open shared object file: No such file or directory
../../../../../home/admin/relion/build/bin/ctffind: error while loading shared libraries: libtiff.so.3: cannot open shared object file: No such file or directory
 WARNING: skipping, since cannot get CTF values for stacks/Motioncor/FoilHole_28648625_Data_28649089_28649090_20170828_1554-2548_MC_DW.mrc
 WARNING: skipping, since cannot get CTF values for stacks/Motioncor/FoilHole_28648625_Data_28649125_28649126_20170828_1555-2549_MC_DW.mrc
 WARNING: skipping, since cannot get CTF values for stacks/Motioncor/FoilHole_28648626_Data_28649528_28649529_20170828_1608-2552_MC_DW.mrc
 WARNING: skipping, since cannot get CTF values for stacks/Motioncor/FoilHole_28648626_Data_28649552_28649553_20170828_1606-2550_MC_DW.mrc
 WARNING: skipping, since cannot get CTF values for stacks/Motioncor/FoilHole_28648626_Data_28649558_28649559_20170828_1606-2551_MC_DW.mrc
 WARNING: skipping, since cannot get CTF values for stacks/Motioncor/FoilHole_28652968_Data_28649552_28649553_20170828_1652-2555_MC_DW.mrc
 WARNING: skipping, since cannot get CTF values for stacks/Motioncor/FoilHole_28654029_Data_28654529_28654530_20170828_1748-2559_MC_DW.mrc
 WARNING: skipping, since cannot get CTF values for stacks/Motioncor/FoilHole_28654029_Data_28654643_28654644_20170828_1746-2557_MC_DW.mrc
 WARNING: skipping, since cannot get CTF values for stacks/Motioncor/FoilHole_28654029_Data_28654652_28654653_20170828_1747-2558_MC_DW.mrc
 WARNING: skipping, since cannot get CTF values for stacks/Motioncor/FoilHole_28654029_Data_28654662_28654663_20170828_1749-2560_MC_DW.mrc
 WARNING: skipping, since cannot get CTF values for stacks/Motioncor/FoilHole_28654029_Data_28654670_28654671_20170828_1745-2556_MC_DW.mrc
 WARNING: skipping, since cannot get CTF values for stacks/Motioncor/FoilHole_28654030_Data_28654670_28654671_20170828_1750-2561_MC_DW.mrc
 WARNING: skipping, since cannot get CTF values for stacks/Motioncor/FoilHole_28654031_Data_28654529_28654530_20170828_1825-2565_MC_DW.mrc
 WARNING: skipping, since cannot get CTF values for stacks/Motioncor/FoilHole_28654031_Data_28654643_28654644_20170828_1823-2563_MC_DW.mrc

runout
 === RELION MPI setup ===
 + Number of MPI processes             = 4
 + Master  (0) runs on host            = gronlund-7910
 + Slave     1 runs on host            = gronlund-7910
 + Slave     2 runs on host            = gronlund-7910
 + Slave     3 runs on host            = gronlund-7910
 =================
--------------------------------------------------------------------------
A system call failed during shared memory initialization that should
not have.  It is likely that your MPI job will now either abort or
experience performance degradation.

  Local host:  gronlund-7910
  System call: open(2) 
  Error:       No such file or directory (errno 2)
--------------------------------------------------------------------------

**Comment by ashkumatov** [comment]
You are missing libtiff lib (it can be sometimes named differently and creating soft link may fix the problem):
error while loading shared libraries: libtiff.so.3: cannot open shared object file: No such file or directory

Alternatively, get the precompiled version of CTFFIND.

HTH, Alex

**Comment by yijianSU22** [comment]
> As the title is, Ctffind4.1 is not working on relion2.1beta(b0 or b1 whatever..)
> 
> Running ctf estimation job with Ctffind4.1 produced empty micrographs_ctf.star file, although Run.err file said just "warning".
> 
> Briefly, two types of warning come; **1) error in executing csh 2) skipping, cannot get CTF value**
> 
> However, Gctf works fine, and therefore I guess this is not simple input error but some problem in relion(specifically, the ctf estimation function or related script?) when it communicates with ctffind4.1. Since I am a kind of novice, I cannot solve out this issue.
> 
> How can I solve out?
> 
> **Remark** : this issue is slightly different with #186 in the following 2 aspects. *_1) The difference to #186 that produced the same errors with my case, is that I could get ctf estimation with Gctf(v1.6) successfully. 2) Plus, nothing have done with ctffind4.1, resulting in empty __ctf.star file. And even repetition of the job did not work at all, which is unlike the solution suggested in #186; repeat this until all micrographs is done.__
> 
> The following are the details of the Note.txt, Run.out and Run.err files.
> 
> ## **Note.txt**
> ## ++++ Executing new job on Fri Aug 18 11:31:23 2017
> ++++ with the following command(s):
> `which relion_run_ctffind` --i ./MotionCorr/job002/corrected_micrographs.star --o CtfFind/job003/ --CS 0.002 --HT 300 --AmpCnst 0.1 --XMAG 10000 --DStep 1.4 --Box 512 --ResMin 30 --ResMax 5 --dFMin 5000 --dFMax 50000 --FStep 500 --dAst 100 --ctffind_exe "/home/sbl/relion_acc/ctffind-4.1.8/ctffind --omp-num-threads 1 --old-school-input" --ctfWin -1 --is_ctffind4
> ++++
> ## **Run.out**
> Using CTFFIND executable in: /home/sbl/relion_acc/ctffind-4.1.8/ctffind --omp-num-threads 1 --old-school-input to estimate CTF parameters for the following micrographs:
> 
> * MotionCorr/job002/rawframes/P97-fullcomplex_0005.mrc
> * MotionCorr/job002/rawframes/P97-fullcomplex_0006.mrc
> * MotionCorr/job002/rawframes/P97-fullcomplex_0007.mrc
>   Estimating CTF parameters using Alexis Rohou's and Niko Grigorieff's CTFFIND4.1 ...
>   0/   0 sec ............................................................~~(,_,">
>   Done! Written out: CtfFind/job003/micrographs_ctf.star
> 
> ## **Run.err**
> ## sh: 1: csh: not found
> WARNING: there was an error in executing: csh CtfFind/job003/rawframes/P97-fullcomplex_0005_ctffind4.com
> sh: 1: csh: not found
> WARNING: there was an error in executing: csh CtfFind/job003/rawframes/P97-fullcomplex_0006_ctffind4.com
> sh: 1: csh: not found
> WARNING: there was an error in executing: csh CtfFind/job003/rawframes/P97-fullcomplex_0007_ctffind4.com
> WARNING: skipping, since cannot get CTF values for MotionCorr/job002/rawframes/P97-fullcomplex_0005.mrc
> WARNING: skipping, since cannot get CTF values for MotionCorr/job002/rawframes/P97-fullcomplex_0006.mrc
> WARNING: skipping, since cannot get CTF values for MotionCorr/job002/rawframes/P97-fullcomplex_0007.mrc

Hey Han
Have you resolved this error when you run relion_run_ctffind in relion2? I met the same error in relion2? Can you give me some suggestions?

Succi

**Comment by biochem-fan** [comment]
Please stop using such an old version of RELION! Use at least RELION 4, ideally 5.

In RELION 4 and later, you can set the `RELION_SHELL` environmental variable to `bash` if you don't have `csh`.
