### ISSUE TITLE
Help messages for CLI

### ISSUE THREAD

**Issue by craigyk** [3dem/relion#292]
The check for required parameters now takes precedence over displaying help information.  I had to run relion_mask_create --i nonsense --help to display the help information.

**Comment by shevegen** [comment]
Off topic but I have this sometimes in my ruby scripts, when I parse commandline options via regexes, and the help-entry point happens very late ... I would even trigger other parts such as "--helpful-messages" or so.  ;-)

Since then I usually make the regex-options stricter in my scripts, that usually helps.

**Comment by dkimanius** [comment]
This is a know issue and the workaround for now is what you suggested: `relion_mask_create --i -h` (you can skip the "nonsense"). It will be fixed in coming releases. We appreciate the feedback.
