### ISSUE TITLE
Does Relion Support CUDA9

### ISSUE THREAD

**Issue by ifelsefi** [3dem/relion#296]
Hi

We were curious if this would compile and run properly under CUDA9?

Thanks!

**Comment by bforsbe** [comment]
There are things which need to be fixed, which does not comply with some new restrictions on synchronization behaviour. There are minor fixes which will be in the stable 2.1 release, which should be out soon. 2.1.b1 does however NOT support cuda 9, officially. It might compile and might even run, but we can't assure that results are trustworthy.  

Some of the new conventions also need some minor adjustments in the code to make maximal use of the hardware. This is because the hardware is still changing alot, which is difficult to anticipate. We tend try to not over-optimize for any single generation of GPUs, but we doe tune the code to work with the most common/often used GPUs. Currently, that means Maxwell and Pascal consumer-level cards. That will probably shift to Pascal and Volta at some point not to far into the future. I'm mentioning this because  the only ral reason to use cuda 9, is to run on Volta-gen cards, which are not really a thing yet, but which will be soon.

**Comment by JusticeForMikeBrown** [comment]
Thanks for explaining @bforsbe!

**Comment by prbprb2** [comment]
Will  relion 3 be using Cuda 9? Thank you

**Comment by JusticeForMikeBrown** [comment]
Hi

Does Relion 3 Beta now support Cuda 9

**Comment by bforsbe** [comment]
Yes, given that you adhere to the compatible compilers and so on.

**Comment by GeemG** [comment]
I have cuda 9 but after installing relion 3 beta I get the warning message

warning relion was compiled without cuda of at least 7 you do not have support for gpu

**Comment by bforsbe** [comment]
Then the cmake-configuration did not detect your CUDA installation. This should be evident from the intial output, saying something like "CUDA not detected, using non-cuda compilation" .

You need to make sure that cmake can find CUDA, how to achieve this depends on your installation and system configuration.
