### ISSUE TITLE
Thon ring evaluation for micrograph selection in relion

### ISSUE THREAD

**Issue by baibing7713661** [3dem/relion#310]
![qq20171110-183509](https://user-images.githubusercontent.com/21249922/32670969-e5f208ca-c645-11e7-9385-5b6ea085e789.png)

I'm selecting the micrograph based on their thon ring profile for particle picking. But I can not find so called quality of fit plot as suggested by Ctffind. So what is the practical rule to select the micrograph based on the tong ring for down-stream analysis. Or which parameter, such as defocus, resolution, figure of merit, should be used for thresholding?
In relion manual "The zeros between the Thon rings in the experimental images should coincide with the ones in the model". But this is rather subjective.

**Comment by bforsbe** [comment]
It IS a subjective procedure. Just like class-selection after 2D and 3D-classification, you either need to 

1. apply a rigorous metric which correctly identifies the micrographs which are reliable and/or representative
2. (subjectively) apply your experience and expertise and argue for why the results are still legitimate. 

I agree that option 1 would be better, but it is very difficult to construct such a metric. Particle selection faces the same challenge; experts do not trust that a non-perfect selection will result in the best possible result. At least, they are typically not willing to take the risk that an automated selection performs as well as an expert. 

There is a quality-metric calculated by most ctf-fitting programs, and you can choose to sort your micrographs based on this "figure of merit" in the relion display-gui, which appears when you run a subset-selection. You can then use "select all above/below" option and trim your selection further if you want. 

A further comment is that the CTFs in your image are all quite poor, since there appears to be very weak and mis-fitted Thon-rings, as well as crystalline ice.
