### ISSUE TITLE
Yet another: No orientation was found as better than any other

### ISSUE THREAD

**Issue by mcahn** [3dem/relion#328]
I cannot get the latest stable RELION to run a 2D classification on the benchmark data.  This may be the same problem I see reported under several other issues.

I downloaded and built the last RELION -- version 2.1 (stable).  When I run the following command on the benchmark data:

srun -n 9 relion_refine_mpi --i Particles/shiny_2sets.star --ctf --iter 25 --tau2_fudge 2 --particle_diameter 360 --K 200 --zero_mask --oversampling 1 --psi_step 6 --offset_range 5 --offset_step 2 --norm --scale --random_seed 0 --o /tigress/CRYOEM/data/relion_benchmark-03/class2d --j 2 --dont_combine_weights_via_disc --pool 40 --scratch_dir /tmp --gpu

it always fails on iteration #6.  It gives this message many times:

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
 WARNING: Exception (ERROR:
    No orientation was found as better than any other.

    A particle image was compared to the reference and resulted in all-zero
    weights (for all orientations). This should not happen, unless your data
    has very special characteristics. This has historically happened for some
    lower-precision calculations, but multiple fallbacks have since been
    implemented. Please report this error to the relion developers at

                     github.com/3dem/relion/issues
     ) handled by switching to fail-safe mode.
    NOTE: No more fail-safe warnings will be issued.

    slave 1 encountered error: ERROR:
    Relion had to use extra-precision fallbacks too many times.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

and then finally:

    application called MPI_Abort(MPI_COMM_WORLD, 1) - process 7

and terminates.

I built RELION with the Intel compiler version 17, with both single- and double-precsion GPU code, and with both the default CUDA_ARCH=35 and the one for our Nvidia P100's, CUDA_ARCH=60.  These builds all behaved the same way.

Let me know if there's anything I can do to help debug this.  The version I was running previously, which was a beta from Nov. 16, **2016**, worked fine.

Regards,
Matthew Cahn
Programmer
Dept. of Molecular Biology
Princeton University
mcahn@princeton.edu

**Comment by bforsbe** [comment]
Did you use CUDA 9?

**Comment by mcahn** [comment]
Yes, I used CUDA 9.

Matthew

**Comment by chenjinkun** [comment]
@mcahn 
Hi，
When I want to built RELION 2.1 stable with Intel compiler vision 17, it tells that RELION only supports Intel compiler vision 16 or 15. Have you met this problem?
And have you fixed the  "No orientation was found as better than any other" problem? I meet the problem too and haven't fixed yet.

Best regards,
Jinkun Chen

**Comment by smsaladi** [comment]
in case it's useful, #323 has a comment that says that there is no extra benefit for using intel with the gpu version

**Comment by biohaznerd** [comment]
Hi,
I am having the same issues with my datasets. I am picking automatically, so I would expect junk in the initial dataset which I want to get rid of by classification. In this respect it would be nice to have this error as a warning, but not as an error and don't put the respective images into any class.
I there any news on that issue, since #242  is still open since June last year?

Best,
Michael

```
slave 3 encountered error: ERROR: 
No orientation was found as better than any other.

A particle image was compared to the reference and resulted in all-zero
weights (for all orientations). This should not happen, unless your data
has very special characteristics. This has historically happened for some 
lower-precision calculations, but multiple fallbacks have since been 
implemented. Please report this error to the relion developers at 

                 github.com/3dem/relion/issues  
 
File: /software/relion-2.1.0/git/src/gpu_utils/cuda_ml_optimiser.cu line: 1710
Dumped data: error_dump_pdf_orientation, error_dump_pdf_orientation and error_dump_unsorted.
Dumped data: error_dump_pdf_orientation, error_dump_pdf_orientation and error_dump_unsorted.
Dumped data: error_dump_pdf_orientation, error_dump_pdf_orientation and error_dump_unsorted.
Dumped data: error_dump_pdf_orientation, error_dump_pdf_orientation and error_dump_unsorted.
```

**Comment by Gunkkk** [comment]
@bforsbe  Is there something odd with  cuda 9 please?

**Comment by bforsbe** [comment]
No there's nothing wrong with CUDA9. 

The issue is that RELION makes the decision to exit if strange things are happening, because it's safer that way. We could just a) ignore bad particles or b) report them as bad. Both options require a decision, which is difficult to establish a general method for. It would be like setting a universal threshold for all datasets; very difficult and almost certainly not universally correct.

The "right" thing to do is to handle these issues with a level of precision which adapts to the circumstance, so that no true/false decisions have to be made. This has been under long-term development, because new corner-cases keep coming up. Every new version of RELION is better at handling these errors, as will the next version be. It might not seem that way for individual users though, because a specific datasets might present unique challenges. Te best advice I can give is to try more robust setting, or possibly a different RELION version, precision and/or choice of CPU vs. GPU.

**Comment by Gunkkk** [comment]
@bforsbe Thank u ! 
Could I ask an extra problem that why the time-consuming expectation-maximization is handled by a small number of  cpus ,just the number of  mpi instead of mpis*threads？
Is there any possibility that handle it with more threads so that the free cpus could be used since the gpu   working time seems that less than the cpu's.
