### ISSUE TITLE
Issue running cuda

### ISSUE THREAD

**Issue by oehlrich9** [3dem/relion#333]
Hey guys,

im running into some problems with starting relion on K20 GPUs with cuda toolkit 8.0

I start relion with the following command:
mpirun -np 4 -npernode 2 ~/relion_build_cuda/bin/relion_refine_mpi --o ~/CudaData/job007/ --i particles.star --ctf --iter 25 --tau2_fudge 2 --particle_diameter 150 --K 100 --flatten_solvent --zero_mask --strict_highres_exp 8 --oversampling 1 --psi_step 12 --offset_range 5 --offset_step 2 --norm --scale --gpu --dont_combine_weights_via_disc --no_parallel_disc_io --pool 60  

After estimating initial noise spectra it returns the error
ERROR: 
Can not close image file

Any idea what could possibly be wrong?

**Comment by bforsbe** [comment]
It is possible that you could see this due to runng the GPU-code, but I am extremely certain this has nothing at all to do with CUDA. The problem is that you cannot close (and write) a file. 

You don't seem to be specifying an output filename, just a directory. Try using 
```
 --o absolute/path/to/CudaData/job007/run
```
 instead of what you are doing now.

**Comment by bforsbe** [comment]
@oehlrich9  Did you get past the problem?
