### ISSUE TITLE
"All-zero weights" in 2D classification and "exotic data or settings" in 3D classification

### ISSUE THREAD

**Issue by Manuela-H** [3dem/relion#339]
Hi there,
I've been using the stable release of Relion2.1 to process a new dataset and have encountered the following errors:

**During 2D classification**: _"A particle image was compared to the reference and resulted in all-zero weights (for all orientations). This should not happen unless your data has very special characteristics. This has historically happened for some lower-precision calculations, but multiple fallbacks have since been implemented. Please report this error to the relion developers..."_

**During 3D classification**: _"Your data or parameters were unexpected: execution on GPUs is subject to many restrictions, and relion is written to work within common restraints. If you have exotic data or settings, unexpected configurations may occur. See also above point regarding double precision. If none of the above applies, please report the error to the relion developers..."_

These data were collected in super-resolution mode, however, all other parameters and the processing steps are identical to what I have done previously (where I had no issues). 

Thanks for any help.
Best regards,
Manuela

**Comment by bforsbe** [comment]
What was the command used in the 3D-classification that generated the message you show? 

If you ran in the GUI, "print command" will display the command in the terminal, or you can "edit note" under job settings, and check the command there.

**Comment by michlun** [comment]
I have also the same issue with the 2D classification. I am running relion 2.1 on a cluster using 10 nodes each one with a GPU (Tesla P100-PCIE-16GB), and the command was:

mpirun --n 21 /opt/em/cuda/relion/2.1/bin/relion_refine_mpi  --o Class2D/job017/run_ct18 --continue Class2D/job017/run_ct16_it018_optimiser.star  --dont_combine_weights_via_disc --pool 3 --ctf --iter 35 --tau2_fudge 2 --particle_diameter 500  --K 200  --flatten_solvent  --zero_mask  --oversampling 1 --psi_step 10 --offset_range 5 --offset_step 2  --norm --scale  --j 10  --gpu >> Class2D/job017/run.out 2>> Class2D/job017/run.err

Shortly after starting the 20th expectation iteration relion stopped reporting about 2200 times the error message:

WARNING: Exception (ERROR: 
No orientation was found as better than any other.

A particle image was compared to the reference and resulted in all-zero
weights (for all orientations). This should not happen, unless your data
has very special characteristics. This has historically happened for some 
lower-precision calculations, but multiple fallbacks have since been 
implemented. Please report this error to the relion developers at 

	         github.com/3dem/relion/issues  
 ) handled by switching to fail-safe mode.

**Comment by michlun** [comment]
I restarted the same job without using the GPU and this time it worked without errors.
