### ISSUE TITLE
supervised classification in relion-2.1.0 

### ISSUE THREAD

**Issue by sarahmariesmith** [3dem/relion#346]
Dear fellow Relion users, 

I have a question regarding supervised 3D classification in relion-2.1.0

I am aware that such classification was possible pre-Relion2 as per, https://www.jiscmail.ac.uk/cgi-bin/webadmin?A2=ind1707&L=CCPEM&P=R39084&1=CCPEM&9=A&I=-3&J=on&d=No+Match%3BMatch%3BMatches&z=4 and https://www.jiscmail.ac.uk/cgi-bin/webadmin?A2=ind1707&L=CCPEM&P=R39084&1=CCPEM&9=A&I=-3&J=on&d=No+Match%3BMatch%3BMatches&z=4 posts on relion jiscmail, and also is something we have implemented successfully ourselves in relion 1.4 (i.e. whole volumes of different cage types are achieved).   

However, repeating such procedure in our current version of relion generates significantly different results. Please see 3DClassification3.png attached for our output. We notice that for 6 out of 10 classes, the output volumes are striated. Previously, we would have interpreted this as an 'orientation preference' of the particles i.e. not enough views of a given cage type. However, we are questioning whether this is now truly the case given our previous success in relion 1.4. 

Also, upon checking the cage library input i.e. in:CagesLibrary.star via the GUI (CageLibrary.png attached) we notice how relion "sees" each of the classification references. Comparing these to our outputs, it seems relion is heavily weighting particle contribution to these particular points/orientations in each volume but isn't able to 'build' a 3D volume from this. Has the reference .star file  been input correctly? (The input command is attached for your reference).      

So, I suppose my question is: are we implementing supervised 3D classification correctly in newer versions of relion? And if so, why are we seeing stark differences in output of 3D classification?   

Any suggestions/comments/questions would be welcomed. 

Many thanks in advance, 
Sarah 

[refine_mpi_command.txt](https://github.com/3dem/relion/files/1796537/refine_mpi_command.txt)
[CageLibrary.txt](https://github.com/3dem/relion/files/1796540/CageLibrary.txt)
![3dclassification3](https://user-images.githubusercontent.com/25389434/37203863-0532f80e-2387-11e8-8d79-eb2430a05457.png)
![cagelibrary](https://user-images.githubusercontent.com/25389434/37203867-0685747a-2387-11e8-9e80-e09fe94d93f6.png)

**Comment by bforsbe** [comment]
Are you using the exact same command with the exact same data? 

Even if you are not, convergence is to some extent stochastic, so running the command twice might not get you the exact same result. I'd say that your interpretation with view-bias is correct, but not in detail: 

You ask the program to "divide the data into classes". Note that this is all you can ask, you are **not** asking relion to "reconstruct as many 3D shapes as possible with even orientation distribution", even though you would like to. If you ask for many classes, it's easier for relion to divide the data based on views rather than object. This is what is happening above. 

I also think your input "cagelib" is far less useful than you think;

1. 10 classes are **a lot** of 3D classes. unlessyou have ~1'000'000 good input particles, relion probably won't be able to make out the difference between 10 classes (you need many particles per class to reconstruct them well enough to tell them apart) 
2. You immediately low-pass filter your inputs to 60Å. They will look fairly similar at that point. 
3. Even if they look very different, any one particle won't look that much like any of them, and so most particles will contribute to ~all classes, which will make them look more similar. Check the first or second iteration output - my guess is that you won't be able to tell them apart. 

If I were you, I'd do the classification hierarchial: 2 classes. Then take the particles from each class and 
subject each to a new classification with 2 classes. This won't allow relion to split data by views, and provides many particles per class, so that it can distinguish classes well enough structurally. You can provide input classes for this as well, but skip the low-pass, it defeats the purpose.
