### ISSUE TITLE
Normalised Probability Greater than 1

### ISSUE THREAD

**Issue by davboyer** [3dem/relion#361]
Hello,

I am having a consistent issue where a 2D Classification will fail with the following error:

Relion is finding a normalised probability greater than 1
File: /home/davboyer/cryoem/relion_02012018/relion/src/gpu_utils/cuda_ml_optimiser.cu line: 2327

Is there any information I can provide to help with this? 

Here is command: `which relion_refine_mpi` --o Class2D/Initial_432_Round8/run --i Select/Initial_432_Round8/particles.star --dont_combine_weights_via_disc --scratch_dir /scratch  --pool 30 --ctf  --iter 25 --tau2_fudge 2 --particle_diameter 456 --K 100 --flatten_solvent  --oversampling 1 --psi_step 3  --offset_range 5 --offset_step 2 --helical_outer_diameter 200 --bimodal_psi --sigma_psi 5 --norm --scale  --j 1 --gpu ""

**Comment by bforsbe** [comment]
Shost in the dark: 
does this still happen without --bimodal_psi (and  --helical_outer_diameter) ?

I'm asking to narrow down what to look for, because after a quick look in the code it's not very obvious what could be causing it. It's obvious that it shouldn't be happening though, so something is clearly not working as intended; thanks for pointing it out!

**Comment by davboyer** [comment]
Hi,

I am trying your suggestion now.

Just to note, this command allowed the job to make it (no normalized probability error). The only difference is I changed psi step from 3 to 2:
 
`which relion_refine_mpi` --o Class2D/Initial_432_Round8/run --i Select/Initial_432_Round8/particles.star --dont_combine_weights_via_disc --scratch_dir /scratch  --pool 30 --ctf  --iter 25 --tau2_fudge 2 --particle_diameter 456 --K 100 --flatten_solvent  --oversampling 1 --psi_step 2  --offset_range 5 --offset_step 2 --helical_outer_diameter 200 --bimodal_psi --sigma_psi 5 --norm --scale  --j 1 --gpu ""

**Comment by davboyer** [comment]
when i run with no bimodal psi and no helix (`which relion_refine_mpi` --o Class2D/Initial_432_Round8/run_debug --i Select/Initial_432_Round8/particles.star --dont_combine_weights_via_disc --scratch_dir /scratch  --pool 30 --ctf  --iter 25 --tau2_fudge 2 --particle_diameter 456 --K 100 --flatten_solvent  --oversampling 1 --psi_step 3  --offset_range 5 --offset_step 2  --sigma_psi 5 --norm --scale  --j 1 --gpu "")

I get a generic error like "File: /home/davboyer/cryoem/relion_02012018/relion/src/gpu_utils/cuda_mem_utils.h line: 94
slave 27 encountered error: ERROR:

A GPU-function failed to execute." Plus I get all the suggestions like "if these happened at beginning of run..." etc.

If I run with helix but no bimodal psi (`which relion_refine_mpi` --o Class2D/Initial_432_Round8/run_debug_2 --i Select/Initial_432_Round8/particles.star --dont_combine_weights_via_disc --scratch_dir /scratch  --pool 30 --ctf  --iter 25 --tau2_fudge 2 --particle_diameter 456 --K 100 --flatten_solvent  --oversampling 1 --psi_step 3  --offset_range 5 --offset_step 2  --sigma_psi 5 --norm --scale  --j 1 --gpu "" --helical_outer_diameter 200), I now get: 

 fn_img= 081756@/scratch/relion_volatile/particles.mrcs
 part_id= 81755
 ipart= 0
 op.min_diff2[ipart]= 2755.74
 group_id= 0
 ml_model.scale_correction[group_id]= 1
 exp_significant_weight[ipart]= 0
 exp_max_weight[ipart]= -1
 ml_model.sigma2_noise[group_id]=
     4e-20
     3e-06
     1e-05
...

The sum of weights for all orientations was
found to be zero for an image. This should not happen, unless your data
has very special characteristics. Please report this error to
the relion developers at.."

Any thoughts?

**Comment by bforsbe** [comment]
It sounds like you've run into non-deterministic errors, i.e. faults that happen by random chance. These are notoriously difficult to track down, and can be due to either;

1. Faults in the structure of the code which cause race-conditions
2. Compiling the code with unsupported software (version-)combinations
3. A novel type of data or launch config, which has not been tested for or foreseen
4. Something else (I've learnt to not proclaim false dichotomies) 

I think we can exclude no.3, and while no.1 is a possibility, I'd like to exclude no.2; so what versions of gcc and CUDA did you use, and which version of relion is this?

Also; do you always hit the same error at the same point when you run rerun with the exact same command?

**Comment by davboyer** [comment]
As for issue 2:

GCC version: 5.4.0
CUDA: 8.0
Relion: 2.1.0 (pulled from github on Feb 1, 2018.)

I will test how many times I can repeat the error with the exact same command. I definitely agree these types of errors I get are non-deterministic, I usually "solve" the problem by running a bunch of similar commands until one works...
