### ISSUE TITLE
KERNEL_ERROR: invalid configuration argument

### ISSUE THREAD

**Issue by davidhoover** [3dem/relion#371]
Hi,

We are seeing an error with 2D classification on GPUs using version 2.1.0.  STDOUT gives this error:

KERNEL_ERROR: invalid configuration argument in /usr/local/apps/RELION/git/2.1.0/src/gpu_utils/cuda_helper_functions.cuh at line 172 (error-code 9)

Here is the commandline that results in this error:

srun --mpi=pmi2 `which relion_refine_mpi` --o Class2D/job013/run --i Extract/job011/particles.star --dont_combine_weights_via_disc --scratch_dir $TMPDIR --pool 3 --ctf  --iter 30 --tau2_fudge 2 --particle_diameter 140 --K 30 --flatten_solvent  --zero_mask  --oversampling 1 --psi_step 12 --offset_range 5 --offset_step 2 --norm --scale  --j 1 --gpu ""

The error seems to be random.  Re-running the job may or may not produce the error.

What should we be looking for to fix this error?

David Hoover
HPC @ NIH

**Comment by bforsbe** [comment]
Hi David,
 
What model GPUs are running this? This is an error we see sometimes during development, or if old GPUs with unexpected hardware restrictions are used. It might be that we ask for a hardcoded amount of on-chip memory that this GPU simply doesn't have. The stochastic nature indicates hardware-issues though, but I shouldn't call it so fast.

**Comment by davidhoover** [comment]
They are NVIDIA Tesla K80s.

David Hoover
HPC @ NIH

**Comment by bforsbe** [comment]
Ill try to reproduce, we have some K80s that we haven't used for quite some time. They're pretty decent cards though. Old, but decent specs. And we have run on them before. I'll have a dig through the code and check which sizes are allocated and whether they are too big. Alternatively you could check yourself and recompile with smaller fixed sizes. Most of them are listed in cuda_settings.h.

Invalid input args could also be due to null pointers, overflow sizes or unexpected dimension. What are the input data dimensions? Ideally I would want a backtrace,  but that might be hard to get(?).

**Comment by biochem-fan** [comment]
Too old issue.
