### ISSUE TITLE
Sphere mask during mask creation

### ISSUE THREAD

**Issue by daniel-s-d-larsson** [3dem/relion#472]
When using "Skip padding" (or --pad 1), the corners can get funny in Refine3D jobs. It would be nice if one could specify a radius in the MaskCreate job type to exclude things beyond that distance. E.g. the flag --outer_radius 150 would remove anything beyond 150 A.

Currently, I do this:
```
if [ ! -e mask_orig.mrc ]; then
    mv mask.mrc mask_orig.mrc
fi

relion_mask_create --denovo --outer_radius 150 --o sphere_mask_150A.mrc --box_size 512 --angpix 1.09

relion_image_handler --i mask_orig.mrc --multiply sphere_mask_150A.mrc --threshold_above 1 --threshold_below 0 --o mask.mrc
```

**Comment by biochem-fan** [comment]
Your script is correct and that is what I would do.

That being said, if your `mask_orig.mrc` is modified by your `relion_image_handler` line, probably your box is too tight. You have problems not only with aliasing but also with signal delocalisation due to CTF. Cannot you down-sample your particles? Are you sure you can reach ~ 2.2 A?

**Comment by biochem-fan** [comment]
In RELION 3.1, one can refine into a smaller box than particles. This means that you can use a large box for particles to avoid aliasing due to interpolation in Fourier space and capture delocalised signals from CTF, and reconstruct into a tight box, saving GPU memory. I hope this makes your life easier.

**Comment by biochem-fan** [comment]
I noticed that you are applying a spherical mask to an existing mask. This is not ideal. You should apply a spherical mask  to the reconstruction (run_class001.mrc) and then use `relion_mask_create`. The reason is that multiplying a mask with a sharp spherical mask might introduce a sharp edge.

I removed `wontfix` tag to think this more carefully. I might implement your suggestion (`--outer_radius`) but this breaks orthogonality of individual tools...
