### ISSUE TITLE
The map looks bad after Bayesian polishing

### ISSUE THREAD

**Issue by cg200678** [3dem/relion#484]
Hi all,

I recently collected a dataset which can be solved to 3.6 A without polishing  and the map is normal. But after I did bayesian polishing and refined the shiny particles, I can see some weird features in the map. The b factator and track seem normal as well. I don't know what caused the problems. I look forward to your suggestions. Thanks.

**Comment by biochem-fan** [comment]
Please run Class2D on shiny particles.

Because Bayesian Polishing does not patch defects, hot pixels and defects *concealed* (not *fixed*; lost information can never be recovered) during initial motion correction come back after Polishing. Particles containing them should be discarded.

In RELION 3.1 (not released yet), Bayesian Polishing can patch defects. But it is unclear whether keeping particles with defects is actually good or not. Having 5 ~ 10 % more suboptimal particles might not give better resolution.

**Comment by cg200678** [comment]
The problem is solved after class2d. Thanks.
