### ISSUE TITLE
Raise max number of subtomograms?

### ISSUE THREAD

**Issue by anaphaze** [3dem/relion#507]
I am running a subtomogram 3-D classification task with 300,000+ subtomograms. I am using RELION 3.0.7 and found that the number of subtomograms copied to the scratch directory is stuck at 100,000. I get this number by counting the number of .mrc files then dividing by 2 to account for the CTF file associated with each subtomogram. The classification job runs, so I'm concerned that only 1/3rd of the dataset is being used.

Is there a parameter that I can edit  to increase the number subtomograms? If so, which file(s) should I edit before rebuilding?

Thanks.
Lu

**Comment by biochem-fan** [comment]
This is already fixed in RELION 3.1, so please wait for its public beta testing (in few weeks).

If you are in hurry, you can fix this by removing `,5` in four places:
https://github.com/3dem/relion/blob/master/src/exp_model.cpp#L561
https://github.com/3dem/relion/blob/master/src/exp_model.cpp#L563
https://github.com/3dem/relion/blob/master/src/exp_model.cpp#L739
https://github.com/3dem/relion/blob/master/src/exp_model.cpp#L746
