### ISSUE TITLE
Post-processing differences

### ISSUE THREAD

**Issue by bforsbe** [3dem/relion#556]
I am trying to diagnose the cause of an unexpected difference in result when post-processing with different relion versions. 

A 3D-refinement was conducted using relion 3.0.2. I then post-process the half-maps using relion 2.1.0, 3.0.2, 3.0.7, and 3.1.beta. In all cases the B-factor and resolution is estimated the same. The intercept of fit is different for 2.1.0, but not by much (-12.61 instead of -13.31). 

The densities are however different. It is perhaps hard to see by the attached figures, but the output from 2.1.0 is very similar to 3.0.x following threshold adjustment, although I have not determined if this is an exact correspondence through a mean/stddev displacement. 

What is VERY clear is that the 3.1.beta output is completely different. I would say it looks oversharpened, but it looks like it's more than that - especially given that the same B-factor is reported as for 2.1.0 and 3.0.x. Having a look at the Guinier-plot it looks like the LogAmplitudesOriginial are different for 3.x compared to 2.1.0, but nothing that would indicate why 3.1.beta looks so different...

![Screenshot_2019-12-16_17-36-58](https://user-images.githubusercontent.com/7627666/70925362-60ec4180-202b-11ea-8a6a-2956213fefa2.png)

Has anything changed with respect to how mrc-files are interpreted in 3.1? Is Post-processing of maps from 3.0.x or earlier using 3.1 not permitted? 

command: 

```
relion_postprocess --i Refine3D/job037/run_half1_class001_unfil.mrc  --o test_output/pp --mask MaskCreate/job038/mask.mrc --angpix 0.86 --auto_bfac  --autob_lowres 10
```

**Comment by biochem-fan** [comment]
Up to RELION 3.0, the output from PostProcess was low-pass filtered at the resolution where FSC is 0.143. This was not optimal, because you still have some signals beyond that. Also you might have some regions whose local resolution is better than others. Thus, RELION 3.1 does not apply hard low-pass filtering any more, only applying FOM weighting.

Probably this is not relevant in your case but also note that RELION 3.1 applies MTF _properly_.  Up to RELION 3.0, PostProcess assumed that the detector pixel size used for MTF correction is the same as that of the map. This is not the case when the particles were down-sampled.

**Comment by bforsbe** [comment]
Adding ```--lowpass -1``` (lowpass to FSC=0.143 resolution) does indeed make the 3.1 post-processed density the same as that of prior relion versions. Thanks!
