### ISSUE TITLE
(3.1) Class2D with multiple box dimensions

### ISSUE THREAD

**Issue by h-ehara** [3dem/relion#566]
**Describe your problem**
Class2D can produce strange results (very blurry or low quality averages) when input star file contains multiple box dimensions.
It seems that the problem is more serious if the difference in box dimensions gets larger.

Example:
Initial optics group looks like this (It's just a single dataset with 9 beam tilts). Class2D works fine with this.
```
_rlnOpticsGroup #1 
_rlnOpticsGroupName #2 
_rlnAmplitudeContrast #3 
_rlnBeamTiltX #4 
_rlnBeamTiltY #5 
_rlnSphericalAberration #6 
_rlnVoltage #7 
_rlnImagePixelSize #8 
_rlnImageSize #9 
_rlnImageDimensionality #10 
           1 opticsGroup1     0.100000     0.145056     -0.39083     2.700000   300.000000     1.050000          336            2 
           2 opticsGroup2     0.100000     -0.15198     0.411734     2.700000   300.000000     1.050000          336            2 
           3 opticsGroup3     0.100000     0.495472     0.222882     2.700000   300.000000     1.050000          336            2 
           4 opticsGroup4     0.100000     -0.49030     -0.21282     2.700000   300.000000     1.050000          336            2 
           5 opticsGroup5     0.100000     0.323592     -0.07479     2.700000   300.000000     1.050000          336            2 
           6 opticsGroup6     0.100000     -0.33327     0.116175     2.700000   300.000000     1.050000          336            2 
           7 opticsGroup7     0.100000     0.162984     0.338954     2.700000   300.000000     1.050000          336            2 
           8 opticsGroup8     0.100000     -0.17355     -0.27689     2.700000   300.000000     1.050000          336            2 
           9 opticsGroup9     0.100000     -0.00412     0.033405     2.700000   300.000000     1.050000          336            2 
```

Then, I added the tenth optics group with a different box size like this. (there is no particle belonging to the group 10)
```
10 opticsGroup10     0.100000     -0.00412     0.033405     2.700000   300.000000     1.050000          420            2 
```

Run Class2D on this dataset, the box dimension is now larger, and the quality is much worse.

Actually, I encountered this problem when I merged K2/K3 data (1.47A/pix and 1.05A/pix), run subtraction with re-windowing(to 200 pixels) and tried to run Class2D on it.
In that case, pixel size was different(with same box size) but I found that the different box dimensions (in angstrom) is probably causing the problem and I'm reporting here the simplified case.
Alternatively, I can possibly evade the problem If I can re-window the K3 data to 200 pixels, and the K2 data to ~140 pixels when subtracting. (Not tried yet.)

**Comment by biochem-fan** [comment]
If you run Class2D separately, does both produce nice class averages instead of many collapsed (blank) classes?

That being said, I don't recommend running Class2D on a merged dataset. Class2D is an indeterministic process and often dominated by difference in ice thickness, MTF difference, etc.

I also recommend you to extract in more-or-less the same pixel size and the box size. Since one dataset is 1.47A/px, there is no point keeping the other at 1.05 A/px. The 1.47 A/px dataset does not contribute to high resolution at all. If your expected resolution is better than 3 A, you should use the 1.05 A/px dataset alone. You might say the 1.47 A/px dataset can still contribute signals at low-to-mid resolution; theoretically yes, but in reality the 1.05 A/px dataset has higher DQE (because of high mag) and dominates.

> In that case, pixel size was different(with same box size) 

Why the box size is different? 

In this case, you want 336 *1.05 = 352 A box. Then I would extract the 1.05 A/px dataset in 336 px, down-sample to 240 px. Now it is 1.47 A/px. The 1.47 A/px dataset should be extracted in 240 px without down-sampling. Then both have the same pixel size and the same pixel size.

If the 1.47 A/px was actually 1.45 A/px, then the second dataset would end up in 200 px, 1.45 A/px. RELION's magnification correction is intended for these tiny differences of 1.47 vs 1.45.

**Comment by h-ehara** [comment]
Thank you for your comment ! & I now understand that Class2D is a complicated process.
Actually, as you say, just downscaling the K3 data to 1.47A/pix might be a better option for me because I want many classes (and not the high resolution), but I just wanted to share the possible issue.

>If you run Class2D separately, do they produce nice class averages instead of many collapsed (blank) classes?

K2 data alone: Nice
K3 data alone: Nice
Merged data: bad
K3 particles selected from the merged data(containing the merged optics group): bad 

>Why the box size is different?
I initially merged these two data:
1.05A/pix, 336pixels K3
1.47A/pix, 240pixels K2

And then, when I did subtraction with re-windowing using that merged data, they became
1.05A/pix, 200pixels K3
1.47A/pix, 200pixels K2
