### ISSUE TITLE
The error from relion3 build with GPU/CPU option

### ISSUE THREAD

**Issue by jianhaoc** [3dem/relion#567]
- OS: Fedora31
 - MPI runtime: openmpi-4.0.2
 - RELION version relion3.0 download with "git clone https://github.com/3dem/relion.git"
 - Memory: 8GB
 - GPU: MX250

```
$ cmake --version
cmake version 3.14.5
$ gcc --version
gcc (GCC) 8.2.0
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:24:38_PDT_2019
Cuda compilation tools, release 10.2, V10.2.89
```

First, I tried to build with `cmake -DCUDA=ON -DCudaTexture=ON ...`.
I ran cmake successfully, but failed to run make (see below).  

```
make[2]: *** [src/apps/CMakeFiles/relion_gpu_util.dir/build.make:65: src/apps/CMakeFiles/relion_gpu_util.dir/__/acc/cuda/relion_gpu_util_generated_cuda_autopicker.cu.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1080: src/apps/CMakeFiles/relion_gpu_util.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
```

Then, I tried to build with `cmake -DALTCPU=ON ...`.
It works with cmake, but still failed with make (see below).

```
make[2]: *** [src/apps/CMakeFiles/relion_lib.dir/build.make:76: src/apps/CMakeFiles/relion_lib.dir/__/acc/cpu/cpu_backprojector.cpp.o] Error 1
make[2]: *** [src/apps/CMakeFiles/relion_lib.dir/build.make:89: src/apps/CMakeFiles/relion_lib.dir/__/acc/cpu/cpu_helper_functions.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:858: src/apps/CMakeFiles/relion_lib.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
```

**Comment by biochem-fan** [comment]
(I fixed your markup)

Please cite the FULL message from the `make` command. It should have printed more information.

**Comment by jianhaoc** [comment]
Full messages are attached.

Below is for "cmake -DCUDA=ON -DCudaTexture=ON .."
[make1.txt](https://github.com/3dem/relion/files/4083673/make1.txt)

Below is for "cmake -DALTCPU=ON .."
[make2.txt](https://github.com/3dem/relion/files/4083674/make2.txt)

**Comment by biochem-fan** [comment]
The error explains what is wrong.

> error: #error -- unsupported GNU version! gcc versions later than 8 are not supported!

However, https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html says the latest CUDA SDK (10.2) supports GCC 8.2.

> x86_64-conda_cos6-linux-gnu-c++ in your PATH

This is because your OpenMPI is compiled with GCC which comes from anaconda. 

Both issues suggest that your compiler setting is messed up. For example, `cmake` might have picked up `mpic` and/or `nvcc` provided by anaconda, which is different from your system-wide installation of `gcc` and `nvcc`. Don't compile RELION within anaconda environment. Make sure what `cmake` picked up the right compiler.
