### ISSUE TITLE
failed to compile the code for benchmarking

### ISSUE THREAD

**Issue by arom4github** [3dem/relion#587]
https://github.com/3dem/relion/blob/ver3.1/src/ml_optimiser_mpi.cpp#L2079
once you select `-DCMAKE_BUILD_TYPE=benchmarking`, the code will fail to compile as there is no `reconstruct` routine with the timer as a parameter. 
See here:  https://github.com/3dem/relion/blob/ver3.1/src/backprojector.cpp#L1337

**Comment by biochem-fan** [comment]
Is this `-DCMAKE_BUILD_TYPE=benchmarking` useful? I have never used it. I instead `#define TIMING` in the program I want to study.

**Comment by arom4github** [comment]
why not using what was already implemented? It's really useful for developing and adaptation

**Comment by bforsbe** [comment]
This was made during the relion-2 dev, but hasn't been properly maintained or systematically implemented. There is also a ```PROFILING``` build type that is really useful for relion_refine (and autopick, if that's of any interest), since you get graphical timelines through the nvidia profiler nvvp. This includes some CPU-blocks.

**Comment by arom4github** [comment]
That's true. You can use NVVP and/or NSightSystems. But you need to collect data first. The time-line could be several GB if you profile real dataset. Working with such so huge files might be not so convenient.  

Well, you are the main developer. So, it's up to you to decide if you want to support this feature or not. From my point of view, if a feature exists, it should be supported. It should be removed if it's not required any more.

**Comment by bforsbe** [comment]
As for the nvvp, we tend to utilize [cudaProfilerStart / Stop](https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__PROFILER.html) to limit profiling to the region of interest and limit trace size. The benefit of open-source is that you can customize this to your need. For profiling of whole runs, there are other tools that do not require intrinsic customization to the code, such as Allinea.  The benchmarking build was an intermediate step to diagnose specific issues, and was never really meant to be a tool for users to optimize performance. From a development standpoint I don't think there's much incentive to spend time cleaning up this currently unused feature so that user may use it, nor do I think its necessarily a good idea since it might be easily fixed if needed in future development.

**Comment by arom4github** [comment]
Ok. I'm closing the issue then
