### ISSUE TITLE
re-extract with re-centering not working?

### ISSUE THREAD

**Issue by craigyk** [3dem/relion#662]
Hi, 

Is re-centering particles during re-extraction not working as expected?  I am not seeing any change to the particle coordinates after re-centering.  I wonder if this is due to the field names changing to: `_rlnOriginXAngst` and `_rlnOriginYAngst`?

I noticed because I've been trying to re-center particles for multiple iterations and yet they seemed stubbornly refusing to budge...

**Comment by craigyk** [comment]
I reverted to 3.1.0 tag, maybe this is a non-issue, or something funny with how OriginAngst converts, rounds and truncates into Coordinates? There are residual looking values left in Origin, even though Coordinates now look like they can use floats.  The coordinate floats were not changing even though the origins were snapping back close to 0.  Mayhaps an integer rounding is occurring before, not after, scaling?

**Comment by biochem-fan** [comment]
I suggest you to define a dummy particle with rot=0, tilt=0, psi=0 and study how OriginAngst and Coordinate change.

If I remember correctly, floating points in CoordinateX/Y are not used by the program. Values from the auto-picking routine are preserved but ignored. Also note that it is very hard to preserve the origin when the box size is changed. It took me weeks to get it right for Polish. I am not sure if it is worth doing for Extract. You should re-refine, because the purpose of re-centering is to find better orientation parameters for the region of interest.

**Comment by craigyk** [comment]
I can imagine- I'm currently not sure with my change if I got the sign correct, will have to double-check, but I was fully intending to re-refine in any case.  The original code was to the effect of:

`
diff = offset - ROUND(offset);
coord -= ROUND(offset);
offset = diff;
`

which I changed to:

`
_coord = coord - offset;
offset = ROUND(_coord) - _coord;
coord = ROUND(_coord);
`
