### ISSUE TITLE
Deny importing files outside the project directory

### ISSUE THREAD

**Issue by biochem-fan** [3dem/relion#697]
In the GUI, reject paths starting from "/" or "../".

**Comment by biochem-fan** [comment]
Checking if a path contains a symbolic link is more complicated.

To use readlink(2) https://www.man7.org/linux/man-pages/man2/readlink.2.html, one has to check all levels in a path.

**Comment by biochem-fan** [comment]
Commit f691d50 addresses half of the problem. Symbolic links are not (yet) tested if they are really by an absolute path.

**Comment by xeniorn** [comment]
Would be great if it doesn't force absolute paths for symbolic links. I understand relative paths breaking the folder structure (e.g. ../), but relative paths inside soft links do not do such things, and issues are rare.

We have multiple machines we use for processing. Not every machine is set up the same way in terms of mounting. So they have different absolute paths for a given relion folder. But the soft link with relative paths work well, because it doesn't matter what the path layers of the location are.

E.g.

/A/B/C/D/relion
/E/F/C/D/relion

having a soft link inside relion pointing to ../../C works normally, but having a soft link to /A/B/C/D/relion would break the usability on the other machines.

Doubly so for any access from Windows computers to the linked context in relion folders. I am not aware of a way to make an absolute path in linux to work on Windows, since it has completely different rules. Relative paths work perfectly in our environment at least.

**Comment by xeniorn** [comment]
"In the GUI, reject paths starting from "/" or "../""

it doesn't prevent stuff like a link to Class2D/../../../source_data.

But probably it shouldn't try to. With every control mechanism like this, there is a danger of breaking a working system somewhere. The most common errors are for sure of the "../" link type.

But also not to break existing systems that people have, a "WARNING" instead of rejection might be better for most cases?

**Comment by biochem-fan** [comment]
Unfortunately, a symbolic link by a relative path can still cause a mess, when RELION tries to expand aliases. I am tired of dealing with many problems (see CCPEM) that could have been avoided if they followed our guidelines.

- https://www3.mrc-lmb.cam.ac.uk/relion/index.php/FAQs#What_is_the_right_way_to_import_files_outside_the_project_directory.3F
- https://www3.mrc-lmb.cam.ac.uk/relion/index.php/FAQs#How_can_I_merge_datasets.2C_potentially_with_different_pixel_sizes.3F

The most common mistake happens when importing raw movies. This commit tries to block it. Making links for individual jobs (like you did) is more advanced case and I hope people know what they are doing. I won't explicitly block it (and you won't Import anyway) but **I will not support any troubles caused from it**.

**Comment by xeniorn** [comment]
That's sensible. It's also the norm as far as I'm aware, even in commercial software - you get support when you use the tool as intended. If you do things outside it, it should be a given that troubleshooting is also on you. The baseline suggestion for such cases is - redo it the supported way.

**Comment by biochem-fan** [comment]
@xeniorn Thanks for your understanding.

Although I cannot promise we can keep it working, can you tell me the details of your use case?

What job do you "bring in" from other project directories? Extract? MotionCorr? Polish? Or raw movies? Do you make links under these job type folders? Do you run an Import job(, which is not necessary)?

**Comment by xeniorn** [comment]
Most of the time what's linked is just the location of the raw micrographs. If another job uses the same raw micrographs, it links directly from the source. And the source = storage is kept separate from the processing folders, they are always linked in.

Sometimes if I'm processing a related dataset, I might bring in 2D refs or 3D refs from there. What I'd have is:
/A/B/relion/(link to C = ../../C)
/A/B/relion/(link to data = C/Refine3D/job.../*class_001.mrc)
/A/C/relion

The idea behind is that there is only 1 link point to any given external source, indiviual data is then linked through the parent link, That way relion is kept separate from the whole linking business, and as far as relion paths go it's all subfolders to the relion root folder.

And they are all subfolders of the relion root folder, as a rule I avoid making links inside job type folders (Class2D/ Refine3D/...) to anything external. Or making folders in there in general - with the exception of some convenient summaries, like a folder containing links to every finished refine3D job run_class001.mrc, but with the job_alias.mrc as the link name, and an equivalently named angularDistribution.png.

I'm not 100 % consistent with import. If I bring in only 1-2 things, I import. If I'm bringing in 10 different tihings of the same type (e.g. various masks), I just use the masks directly from the linked folder (relion/masks pointing to wherever the shared masks are).

Or if I want to process something differently but not start from scratch, I might link the motion corr micrographs, or particles, or both. Then it's usually linking the micrographs / mrcs, and copying the micros/partices.star file, and editing it if necessary to fit to the different path structure (e.g. particles.star pointing to external/location/*mrc as the rlnMicrographImage instead of MotionCorr/jobxxx/..., since the job numbers wouldn't match typically and I definitely don't want to make a  "fake job003" in the current relion project folder.

Generally the idea is to at the same time avoid data duplication and avoid having enormous unwieldy relion projects with hundreds of jobs.

**Comment by biochem-fan** [comment]
@xeniorn 

> Most of the time what's linked is just the location of the raw micrographs

This is dangerous, where you can introduce `../../001.tif` that causes a mess in Extract and others. See https://www3.mrc-lmb.cam.ac.uk/relion/index.php/FAQs#What_is_the_right_way_to_import_files_outside_the_project_directory.3F.

```
ln -s ../../storage/dataset1 dataset1
# then import dataset1/*.tif
```

Is this what you do? Does it work until the end (including Polish)? If so, this is a good news and I will update the wiki.

> I might bring in 2D refs or 3D refs from there.

This is safe.

> Or if I want to process something differently but not start from scratch, I might link the motion corr micrographs, or particles, or both. Then it's usually linking the micrographs / mrcs, and copying the micros/partices.star file, and editing it if necessary to fit to the different path structure (e.g. particles.star pointing to external/location/*mrc as the rlnMicrographImage instead of MotionCorr/jobxxx/..., since the job numbers wouldn't match typically and I definitely don't want to make a "fake job003" in the current relion project folder.

This is the most dangerous.

```
ln -s ../../other_project/MotionCorr/job003 external_motion_corr
cp external_motion_corr/corrected_micrographs.star external_mics_fixed_path.star
sed -i ... external_mics_fixed_path.star # replace rlnMicrographImage paths
```

Is this what you do?

In normal operation, when RELION sees `MotionCorr/job003/dataset1/001.mrc`, it trims the first two directories to get `dataset1/001.mrc`, which is used in Extract, AutoPick, Polish etc. So you will get `Extract/job004/dataset1/001.mrcs`.

When rlnMicrographImage is `external_motion_corr/dataset1/001.mrc`, I tried to make RELION use the whole thing, without trimming, such that you will get `Extract/job004/external_motion_corr/dataset1/001.mrcs`. But there are many corner cases and I cannot guarantee it always works.

For example, if you do

```
ln -s ../../other_project/MotionCorr external_motion_corr
```
instead, probably `external_motion_corr/job003/dataset1/001.mrc` will be trimmed to `dataset1/001.mrc` (because the second folder starts from `job`). The difference of `Extract/job004/external_motion_corr/dataset1/001.mrcs` and `Extract/job004/dataset1/001.mrcs` matters, because coordinate STAR files are searched in the corresponding folder: `AutoPick/job002/external_motion_corr/dataset1/001_autopick.star` vs `Extract/job002/dataset1/001_autopick.star`. Similar issues exist for re-extraction from existing run_data.star.

Apparently you found your own way to avoid these issues but please bear in mind this is very fragile and unsupported.

**Comment by xeniorn** [comment]
```
ln -s ../../storage/dataset1 dataset1
# then import dataset1/*.tif
Is this what you do? Does it work until the end (including Polish)? If so, this is a good news and I will update the wiki.
```
Yes, it's what I have been using in 90 % of cases since 2018. It never had any issues, incl Polish, Subtract, MultiBody, ...

The other 10 % of the cases was creating a folder raw_micrographs inside of relion folder, and inside that folder creating individual soft links, or sometimes hard links, to where the data is, as a relative path (../(......)/[dataFolder]/micrograph1.tif). For this case I'm almost certain it never had an issue but I can't guarantee it.

*************************************

importing motion corr stuff from another project (typically when I want to merge the data from project A and project B, and I do it in project C rather than either A or B):

```
mkdir relion_C/,motionCorA/
(for file in $(ls motionCorA/jobXXX/[extraPath]/*mrc | grep -v _PS.mrc); do ln -s $file relion_C/motionCorA/; done)
(possibly repeat for the motion cor metadata to allow polishing)
mkdir relion_C/,motionCorB/
(repeat equivalently)
```

I will generally avoid linking the whole folder when all I need are the files. 
This also worked. I only ran into trouble when trying to re-polish two merged datasets simultaneously, after they were combined into a single star file for combined refinement. That seemed not to work, but I assumed this is simply not possible yet, i.e. that relion doesn't know how to separate things correctly in this case. I forgot the details by now. But since it was rather exotic use of the software I didn't consider reporting it.

****************************

Regarding your "danger use cases" - thanks for the clarification, I wasn't aware this was handled explicitly based on folder name. I intuitively avoided that - i.e. I would never link external_motion_corr like that. Especially I would never have anything inside relion go to anything named "/jobXXX/", as I consider it a reserved pattern for relion that tells me it belongs to this instance of relion. I generally:

1) link the root folder of the other relion project (ln -s ../../../other_relion local_name_for_other_relion), or similarly any extrnal resource
2a) create a soft link to local_name_for_external_resource/target_resource, or
2b) create a sub folder, and then links inside there to many external_resource/target_resource

That's for any links from "live" locations, like relion project folders, and similarly from other software.
When it's a "dumb" location such as the raw micrographs location on storage, I just link to the raw_micrographs folder

****************************

A minor quirk - if you're indeed filtering for folders staring with "job" in the second level of the path, probably it should be restricted to those where the second folder fits job[0-9]{3-4} regex, or job[0-9]+ regex or similar - i.e. constrain it to only those which relion actually can create. To eliminate the odd case when someone has a folder named job[not a number], which might be their name or their protein's name

****************************

Hope it helps

**Comment by biochem-fan** [comment]
> A minor quirk - if you're indeed filtering for folders staring with "job" in the second level of the path, probably it should be restricted to those where the second folder fits job[0-9]{3-4} regex, or job[0-9]+ regex 

This is true but not exhaustive; this becomes an end-less corner case hunting (and C++ does not have built-in regex). Thus we decided to leave this unsupported.
