### ISSUE TITLE
mpi issue (again)

### ISSUE THREAD

**Issue by jhansen6** [3dem/relion#746]
hi I may have already posted this, issue is still unresolved.   We are processing data on our local cluster running centOS.  I am running a polishing job of ~200k particles (box size 400px; ~1A/px) and it crashes.  I am running on nodes of 24 CPUs (250GB memory).   If I submit to one node with --np 24 --j 1 it crashes, same with --np 12 --j 4, and same with --np 6 --j 4.  However it WILL run with --np 4 --j 6, but estimated completion is ~80 hours.  It definitely also fails when I try to spread the job out on multiple nodes (e.g. using 48 CPUs on two 24 CPU nodes). Meanwhile others in our department have reported success while running on multiple nodes with many processors.  This makes me think it's not an issue with our cluster.  No idea what I could be doing wrong, I copied the script from someone who has had success and put in my own maps etc...  it ran a bit longer but still eventually failed.  The main difference it seems was adding the flag "--map-by node" which helped a bit.   

relion 3.1-gnu
openmpi/1.8.4

Error: 
--------------------------------------------------------------------------

WARNING: A process refused to die despite all the efforts!

This process may still be running and/or consuming resources.

Host: emnode2902

PID:  18884

--------------------------------------------------------------------------

[emnode2902:18879] 1 more process has sent help message help-orte-odls-base.txt / orte-odls-base:could-not-kill

[emnode2902:18879] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages

51/75

63/75

71/75

33/75

70/75

9/75

58/75

[emnode2902:18879] 1 more process has sent help message help-orte-odls-base.txt / orte-odls-base:could-not-kill

[emnode2902:18879] 1 more process has sent help message help-orte-odls-base.txt / orte-odls-base:could-not-kill

39/75

[emnode2902:18879] 3 more processes have sent help message help-orte-odls-base.txt / orte-odls-base:could-not-kill

--------------------------------------------------------------------------

mpirun noticed that process rank 5 with PID 0 on node emnode3202 exited on signal 9 (Killed).

--------------------------------------------------------------------------

[emnode2902:18879] 3 more processes have sent help message help-orte-odls-base.txt / orte-odls-base:could-not-kill

"polish.log" 6691L, 95994C                                                                                              

job file:
mpirun --map-by node --np 4 relion_motion_refine_mpi --i Refine3D/job001/run_data.star --fdose 1.15 --f PostProcess/job003/postprocess.star  --corr_mic MotionCorr/job002/corrected_micrographs.star --first_frame 1 --last_frame -1 --o Polish/job003/ --params_file Polish/job003/opt_params_all_groups.txt --combine_frames --bfac_minfreq 20 --bfac_maxfreq -1 --window 640 --scale 320 --j 6  --pipeline_control Polish/job003/ &>polish.log

**Comment by biochem-fan** [comment]
> --np 24 --j 1 it crashes, same with --np 12 --j 4, and same with --np 6 --j 4. However it WILL run with --np 4 --j 6

This suggests you are running out of memory.

You can run only 4 processes / 250 GB. This is not unexpected for large movies, many particles/movie and/or large boxes.

>  I try to spread the job out on multiple nodes (e.g. using 48 CPUs on two 24 CPU nodes).

How did you do it? Did you check the beginning of `run.out` and confirm that MPI processes are spread
evenly on the nodes?

> The main difference it seems was adding the flag "--map-by node" which helped a bit.

This also supports my view above.

Suppose you want to use 2 nodes. Because you can run up to 4 processes/250GB, you can
run 8 MPI processes, 6 threads/process over 2 nodes.

Obviously we want to place 4 processes per node. But if your job manager (SGE, SLURM, etc)
and/or job submission script are not configured properly, all 8 processes can end up on one single node
and the other node is completely idle. Now the job crashes, as it runs out of the memory on the first node.
`--map-by node` tries to force the former (desired) behavior but not always if the job system is incorrectly configured.
