### ISSUE TITLE
update cmake scripts to use oneAPI and oneTBB

### ISSUE THREAD

**Issue by davidhoover** [3dem/relion#879]
Is there any hope of updating the relion cmake scripts to use oneAPI and oneTBB?

**Comment by biochem-fan** [comment]
You can use the classic intel compiler that comes free with the oneAPI HPC toolkit. The new compiler (based on LLVM) should work as well but was not tested.

Or, do you mean using oneAPI+oneTBB instead of CUDA to use Intel GPUs? That would need whole re-write of computational kernels and won't happen in near future.

**Comment by do-jason** [comment]
@davidhoover I would recommend using Intel classic compiler(icpc) for performance perspective. In my experiment, Intel classic compiler is much faster than oneAPI compiler so far. Do you want to just check oneAPI compilation?
