### ISSUE TITLE
mrc header stats not set in postprocessing locres

### ISSUE THREAD

**Issue by bforsbe** [3dem/relion#921]
The map min/max values are incorrect in the locres-filtered output, and I believe this is due to a missing call to `setStatisticsInHeader` on both I1 and I2 objects here   
https://github.com/3dem/relion/blob/04079953afd9f74c8705e24004091575b4fd71e0/src/postprocessing.cpp#L1184

instead of just `setSamplingRateInHeader`

On a related note, the the locres-filtered output seems to have map values double that of the input. A missing FFT normalization after pad=2 somewhere? I'm just guessing, and this is a single observation.

**Comment by biochem-fan** [comment]
min/max: you are right. Can you send me a pull request? Or I will fix it myself.

> the the locres-filtered output seems to have map values double that of the input.

Does this matter? The absolute scale of a cryo-EM map is kind-of arbitrary due to various normalizations and MTF during processing. When one uses a locres filtered map as an initial model, they should answer the "absolute gray scale" question to "No" anyway.

**Comment by biochem-fan** [comment]
> Can you send me a pull request? Or I will fix it myself.

Because there was no response, I went ahead and fixed both issues as suggested.
