### ISSUE TITLE
Plot topaz training metrics

### ISSUE THREAD

**Issue by Guillawme** [3dem/relion#929]
Hello,

Here is a suggestion for a small improvement in user experience: it would be nice to have a logfile.pdf in the outputs of topaz training jobs, which would contain the plots of all metrics present in the `model_training.txt` file (each metric plotted as a function of `iter`, not `epoch`, as this produces smoother curves; also with two curves for `test` and `train` where relevant).

This is of course low priority compared to bug reports and new developments.

**Comment by biochem-fan** [comment]
Your suggestion is valid but I would leave this to Topaz developers, because:

- this is much easier to implement in Python than in C++
- we want to make our wrappers as simple as possible to minimize future maintenance burdens (i.e. what happens when Topaz changes the columns in the log file?)
- your suggestion relates to all Topaz users, not only to RELION users

**Comment by Guillawme** [comment]
Fair enough. 👍 

For people landing here while searching for how to do this, here's a tool I made: https://github.com/Guillawme/topaztrainmetrics
Better than nothing, but I am not fully satisfied of it: I would prefer a single command plotting all the data (I might update it when I find some time).
