### ISSUE TITLE
Questions about the installation procedure of 5.0-beta

### ISSUE THREAD

**Issue by kttn8769** [3dem/relion#997]
Hi,

I have two questions regarding the installation of 5.0-beta.

**1. Where are the automatically downloaded model weights?**
https://github.com/3dem/relion/blob/08be2f1442dd1b3db19aabb083187d5d7325a593/README.md?plain=1#L49-L52
I have installed the RELION Python dependencies, but I don't know where do the automatically downloaded weights exist.

**2. Should I really deactivate the conda environment?**
https://github.com/3dem/relion/blob/08be2f1442dd1b3db19aabb083187d5d7325a593/README.md?plain=1#L55-L56
Even the relion-5.0 conda environment (which was created by `conda env create -f environment.yml`) should be deactivated before installation?

**Comment by biochem-fan** [comment]
> 1. Where are the automatically downloaded model weights?

This is printed during `cmake`:

```
-- Found Conda environment (name: relion-5.0) and its Python executable.
-- Using Python executable: /home1/app/.conda/envs/relion-5.0/bin/python
-- Will try to find Torch home directory...
-- Using Torch home: /home1/app/.cache/torch
```

You can also get the default path by running 

```
python3 -c "import torch; print(torch.hub._get_torch_home())
```

after activating the `relion-5.0` conda environment.

> 2. Should I really deactivate the conda environment?

Yes, although not absolutely necessary. If you know what you are doing, you are free to take the risk.

Deactivating conda prevents cmake from linking RELION against libraries provided by conda.
In the past, many people reported problems caused by GCC, CUDA, OpenMPI etc provided by conda being incomplete and/or incompatible with the system.

**Comment by alburse** [comment]
Run something like this

**Comment by kttn8769** [comment]
Thank you @biochem-fan @alburse.
After deactivating conda, cmake automatically found the relion-5.0 env and downloaded the model weights without even specifying DPYTHON_EXE_PATH and DPYTHON_HOME_PATH.
